### PR TITLE
C support

### PR DESCRIPTION
**Pull request by thekingofpython**
hi i wanna test github

### CODE REVIEW

**Comment by SirCmpwn** [comment]
What?

**Comment by thekingofpython** [comment]
u know how i can fix others scripts?
and be a ccontributor ?

im new to here 

i wanna in the main goal to help others in open source 
i good in python

**Comment by thekingofpython** [comment]
budy?

**Comment by Ivoah** [comment]
If you want to help with KOS, look at the issues list and see if there's anything you think you can do: https://github.com/KnightOS/KnightOS/issues

**Comment by thekingofpython** [comment]
thanks =] 

and u know how i join to be a contributor ?

**Pull request closed without merging**
