### PR TITLE
Fix build-ci

### PR DESCRIPTION
**Pull request by aviallon**
Use kpack-git instead of kpack
Fix a few mistakes

### CODE REVIEW

**Comment by aviallon** [comment]
Niiice

**Comment by aviallon** [comment]
#388 can finally be closed :confetti_ball: :grinning:

**Comment by pixelherodev** [comment]
Not quite, there's still some packages without individual CI.

**Comment by aviallon** [comment]
> Not quite, there's still some packages without individual CI.

Oh, forgot about them :P

**Pull request merged**
